datasources: 
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: loki
      type: loki
      url: http://my-loki-gateway.loki.svc.cluster.local
      access: proxy
      isDefault: true
      editable: true
    - name: Mimir-Pods-Tenant
      type: prometheus
      access: proxy
      orgId: 1
      url: http://my-mimir-nginx.mimir.svc:80/prometheus
      version: 1
      editalbe: true
      jsonData:
        httpHeaderName1: "X-Scope-OrgID"
        alertmanagerUid: "alertmanager"
      secureJsonData:
        httpHeaderValue1: "pods"
    - name: Mimir-Nodes-Tenant
      type: prometheus
      access: proxy
      orgId: 1
      url: http://my-mimir-nginx.mimir.svc:80/prometheus
      version: 1
      editable: true
      jsonData:
        httpHeaderName1: "X-Scope-OrgID"
        alertmanagerUid: "alertmanager"
      secureJsonData:
        httpHeaderValue1: "nodes"
    - name: Mimir-Alertmanager
      uid: alertmanager
      type: alertmanager
      access: proxy
      orgId: 1
      url: http://my-mimir-nginx.mimir.svc:80
      version: 1
      jsonData:
        implementation: "cortex"
