storage:
  trace:
    backend: s3
    s3:
      bucket: 'tempo-traces'
      insecure: true  
      endpoint: 'my-minio.storage.svc.cluster.local:9000'
      secret_key: 'r9qffGHCTAGjUUeoSArPoneDxlKBQ1fwMIwNO7rG'
      access_key: 'dnC8MQpIk4rDG0LQ2xE1'

minio:
  enabled: false

traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
  zipkin:
    enabled: false
  jaeger:
    thriftHttp:
      enabled: false
  opencensus:
    enabled: false
