server:
        #  service#:
        #    type: NodePort
        #    nodePortHttp: 32073
        #    nodePortHttps: 32074
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    ingressClassName: "nginx"

    path: /
    pathType: Prefix

    tls: true


