query_scheduler:
  replicas: 1
querier:
  replicas: 1
alertmanager:
        #  fallbackConfig: |
          #    receivers:
            #      - name: 'slack-notifications'
            #        slack_configs:
            #          - channel: '#alerts'
            #            text: '{{ template "slack.myorg.text" . }}'
            #    route:
            #      receiver: 'slack-notifications'
  persistentVolume:
    storageClass: hostpath

ingester:
  zoneAwareReplication:
    enabled: false
  persistentVolume:
    storageClass: hostpath

store_gateway:
  zoneAwareReplication:
    enabled: false
  persistentVolume:
    storageClass: hostpath

minio:
  enabled: false
mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          access_key_id: dnC8MQpIk4rDG0LQ2xE1 
          bucket_name: mimir-ruler
          endpoint: my-minio.storage.svc.cluster.local:9000
          insecure: true
          secret_access_key: r9qffGHCTAGjUUeoSArPoneDxlKBQ1fwMIwNO7rG 
    blocks_storage:
      s3:
        bucket_name: mimir-tsdb
    alertmanager_storage:
      s3:
        bucket_name: mimir-ruler
    ruler_storage:
      s3:
        bucket_name: mimir-ruler
