read:
  replicas: 1
  persistance:
    storageClass: longhorn

write:
  replicas: 1
  persistance:
    storageClass: longhorn

backend:
  replicas: 1
  persistance:
    storageClass: longhorn


loki:
  schemaConfig:
    configs:
      - from: 2024-04-01
        object_store: s3
        store: tsdb
        schema: v13
        index:
          prefix: index_
          period: 24h
        chunks:
          period: 24h
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    type: s3
    s3:
      endpoint: http://my-minio.minio.svc.cluster.local:9000
      region: ap-northeast-2
      secretAccessKey: IHTYs1KOFUHUcwE3FDmXZZqlenHZBlQwjvzEIxKo
      accessKeyId: 0rqSx7AIpUZSr1i0A2ER
      signatureVersion: null
      s3ForcePathStyle: true
      insecure: true

